SET ECHO ON

drop table MOVIE_APACHE_COMBINED_LOG;

create table MOVIE_APACHE_COMBINED_LOG
(
CLIENT_IP_ADDRESS VARCHAR2(15),
CLIENT_ID VARCHAR2(40),
REMOTE_USER_ID VARCHAR2(40),
REQUEST_DATE DATE,
REQUEST_LINE VARCHAR(3000),
RETURN_STATUS_CODE NUMBER,
RETURN_SIZE VARCHAR2(20),
REFERER VARCHAR2(3000),
USER_AGENT VARCHAR2(3000)
) partition by hash(REQUEST_DATE) partitions 2;

SET ECHO OFF
